[package]
name = "axsignal"
version = "0.2.0"
edition = "2024"
authors = [
    "Mivik <mivikq@gmail.com>",
    "Asakura Mizu <asakuramizu111@gmail.com>",
]
repository = "https://github.com/Starry-OS/axsignal"

[dependencies]
axcpu = "0.2"
axplat = "0.1"
bitflags = "2.6"
cfg-if = "1.0.0"
derive_more = { version = "2.0.1", default-features = false, features = [
    "full",
] }
linux-raw-sys = { version = "0.9.3", default-features = false, features = [
    "general",
    "no_std",
] }
lock_api = "0.4.12"
log = "0.4"
strum_macros = "0.27.1"

[patch.crates-io]
axcpu = { git = "https://github.com/Starry-Mix-THU/axcpu.git" }
